Outputs:
  SampleCloudFormationServiceRoleArn:
    Export:
      Name: sample-cloud-formation-service-role-arn
    Value: !GetAtt 'SampleCloudFormationServiceRole.Arn'
  SampleCodeBuildServiceRoleArn:
    Export:
      Name: sample-code-build-service-role-arn
    Value: !GetAtt 'SampleCodeBuildServiceRole.Arn'
  SampleCodePipelineServiceRoleArn:
    Export:
      Name: sample-code-pipeline-service-role-arn
    Value: !GetAtt 'SampleCodePipelineServiceRole.Arn'
  SampleLambdaEdgeServiceRoleArn:
    Export:
      Name: sample-lambda-edge-service-role-arn
    Value: !GetAtt 'SampleLambdaEdgeServiceRole.Arn'
  SampleLambdaServiceRoleArn:
    Export:
      Name: sample-lambda-service-role-arn
    Value: !GetAtt 'SampleLambdaServiceRole.Arn'
Resources:
  SampleCloudFormationServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - cloudformation:*
                  - iam:*
                  - lambda:*
                  - s3:*
                Effect: Allow
                Resource:
                  - '*'
            Version: '2012-10-17'
          PolicyName: sample-cloudformation-policy
      RoleName: sample-cloudformation-service-role
    Type: AWS::IAM::Role
  SampleCodeBuildServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:*
                  - s3:*
                Effect: Allow
                Resource:
                  - '*'
            Version: '2012-10-17'
          PolicyName: sample-codebuild-policy
      RoleName: sample-codebuild-service-role
    Type: AWS::IAM::Role
  SampleCodePipelineServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - cloudformation:*
                  - codebuild:*
                  - iam:*
                  - s3:*
                Effect: Allow
                Resource:
                  - '*'
            Version: '2012-10-17'
          PolicyName: sample-codepipeline-policy
      RoleName: sample-codepipeline-service-role
    Type: AWS::IAM::Role
  SampleLambdaEdgeServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action: lambda:*
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: sample-policy
      RoleName: sample-lambda-edge-service-role
    Type: AWS::IAM::Role
  SampleLambdaServiceRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Path: /
      Policies:
        - PolicyDocument:
            Statement:
              - Action: lambda:*
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: sample-policy
      RoleName: sample-lambda-service-role
    Type: AWS::IAM::Role
