Parameters:
  PrivateSubnetCidrA:
    Default: 10.0.2.0/24
    Type: String
  PrivateSubnetCidrB:
    Default: 10.0.3.0/24
    Type: String
  PublicSubnetCidrA:
    Default: 10.0.0.0/24
    Type: String
  PublicSubnetCidrB:
    Default: 10.0.1.0/24
    Type: String
  VpcCidr:
    Default: 10.0.0.0/16
    Type: String
Resources:
  SampleAttachment:
    Properties:
      InternetGatewayId: !Ref 'SampleIgw'
      VpcId: !Ref 'SampleVpc'
    Type: AWS::EC2::VPCGatewayAttachment
  SampleIgw:
    Type: AWS::EC2::InternetGateway
  SamplePrivateRoteTable:
    Properties:
      VpcId: !Ref 'SampleVpc'
    Type: AWS::EC2::RouteTable
  SamplePrivateRoteTableAssociationA:
    Properties:
      RouteTableId: !Ref 'SamplePrivateRoteTable'
      SubnetId: !Ref 'SamplePrivateSubnetA'
    Type: AWS::EC2::SubnetRouteTableAssociation
  SamplePrivateRoteTableAssociationB:
    Properties:
      RouteTableId: !Ref 'SamplePrivateRoteTable'
      SubnetId: !Ref 'SamplePrivateSubnetB'
    Type: AWS::EC2::SubnetRouteTableAssociation
  SamplePrivateSubnetA:
    Properties:
      AvailabilityZone: !Sub '${AWS::Region}a'
      CidrBlock: !Ref 'PrivateSubnetCidrA'
      VpcId: !Ref 'SampleVpc'
    Type: AWS::EC2::Subnet
  SamplePrivateSubnetB:
    Properties:
      AvailabilityZone: !Sub '${AWS::Region}b'
      CidrBlock: !Ref 'PrivateSubnetCidrB'
      VpcId: !Ref 'SampleVpc'
    Type: AWS::EC2::Subnet
  SamplePublicRoteTable:
    Properties:
      VpcId: !Ref 'SampleVpc'
    Type: AWS::EC2::RouteTable
  SamplePublicRoteTableAssociationA:
    Properties:
      RouteTableId: !Ref 'SamplePublicRoteTable'
      SubnetId: !Ref 'SamplePublicSubnetA'
    Type: AWS::EC2::SubnetRouteTableAssociation
  SamplePublicRoteTableAssociationB:
    Properties:
      RouteTableId: !Ref 'SamplePublicRoteTable'
      SubnetId: !Ref 'SamplePublicSubnetB'
    Type: AWS::EC2::SubnetRouteTableAssociation
  SamplePublicRoute:
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref 'SampleIgw'
      RouteTableId: !Ref 'SamplePublicRoteTable'
    Type: AWS::EC2::Route
  SamplePublicSubnetA:
    Properties:
      AvailabilityZone: !Sub '${AWS::Region}a'
      CidrBlock: !Ref 'PublicSubnetCidrA'
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref 'SampleVpc'
    Type: AWS::EC2::Subnet
  SamplePublicSubnetB:
    Properties:
      AvailabilityZone: !Sub '${AWS::Region}b'
      CidrBlock: !Ref 'PublicSubnetCidrB'
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref 'SampleVpc'
    Type: AWS::EC2::Subnet
  SampleVpc:
    Properties:
      CidrBlock: !Ref 'VpcCidr'
    Type: AWS::EC2::VPC
