Outputs:
  SampleAlbSecurityGroup:
    Export:
      Name: sample-fargate-alb-security-group
    Value: !Ref 'SampleAlbSecurityGroup'
  SampleTaskSecurityGroup:
    Export:
      Name: sample-fargate-task-security-group
    Value: !Ref 'SampleTaskSecurityGroup'
Resources:
  SampleAlbSecurityGroup:
    Properties:
      GroupDescription: sample-fargate
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
      VpcId: !ImportValue 'sample-vpc-id'
    Type: AWS::EC2::SecurityGroup
  SampleTaskSecurityGroup:
    Properties:
      GroupDescription: sample-fargate
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
      VpcId: !ImportValue 'sample-vpc-id'
    Type: AWS::EC2::SecurityGroup
