basePath: ''
definitions:
  Empty:
    title: Empty Schema
    type: object
paths:
  {path}:
    {method}:
      produces:
      - application/json
      responses:
        200:
          description: 200 response
        400:
          description: 400 response
        401:
          description: 401 response
        402:
          description: 402 response
        403:
          description: 403 response
        404:
          description: 404 response
        500:
          description: 500 response
      x-amazon-apigateway-integration:
        contentHandling: CONVERT_TO_TEXT
        httpMethod: POST
        passthroughBehavior: when_no_match
        responses:
          default:
            statusCode: '200'
        type: aws_proxy
        uri: {uri}
schemes:
- https
swagger: '2.0'
