version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

    commands:
      - pip install --upgrade pip
      - pip install -r ./sample015/requirements.txt

  pre_build:
    commands:
      - python3 -m pytest
