Parameters:
  BuildSpecPath:
    Default: buildspec.yml
    Type: String
  GitHubToken:
    Type: String
  GitHubUrl:
    Type: String
Resources:
  SampleBuildProject:
    Properties:
      Artifacts:
        Location: !ImportValue 'sample-bucket-name'
        Name: sample
        Type: S3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: S3_BUCKET
            Value: !ImportValue 'sample-bucket-name'
        Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
        Type: LINUX_CONTAINER
      Name: sample-codepipeline-project
      ServiceRole: !ImportValue 'sample-code-build-service-role-arn'
      Source:
        BuildSpec: !Ref 'BuildSpecPath'
        Location: !Ref 'GitHubUrl'
        Type: GITHUB
      Triggers:
        Webhook: 'true'
    Type: AWS::CodeBuild::Project
