Parameters:
  BuildSpecPath:
    Default: buildspec.yml
    Type: String
  GitHubUrl:
    Type: String
Resources:
  SampleBuildProject:
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
        Type: LINUX_CONTAINER
      Name: sample-codepipeline-project
      ServiceRole: !ImportValue 'sample-code-build-service-role-arn'
      Source:
        Auth:
          Type: OAUTH
        BuildSpec: !Ref 'BuildSpecPath'
        Location: !Ref 'GitHubUrl'
        ReportBuildStatus: 'true'
        Type: GITHUB
      Triggers:
        Webhook: 'true'
    Type: AWS::CodeBuild::Project
