Resources:
  SampleLambdaFunction:
    Properties:
      CodeUri: .
      FunctionName: sample-lambda-function
      Handler: lambda_function.lambda_handler
      Role: !ImportValue 'sample-lambda-service-role-arn'
      Runtime: python3.7
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
