Parameters:
  AcmCertificateArn:
    Type: String
  Cname:
    Type: String
  HostZoneId:
    Type: String
Resources:
  SampleBucket:
    Properties:
      BucketName: !Sub 'sample-bucket-${AWS::AccountId}'
    Type: AWS::S3::Bucket
  SampleBucketPolicy:
    Properties:
      Bucket: !Ref 'SampleBucket'
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt 'SampleOriginAccessIdentity.S3CanonicalUserId'
            Resource: !Join
              - /
              - - !GetAtt 'SampleBucket.Arn'
                - '*'
    Type: AWS::S3::BucketPolicy
  SampleDistribution:
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref 'Cname'
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: 'true'
          TargetOriginId: !Sub 'S3-${SampleBucket}'
          ViewerProtocolPolicy: redirect-to-https
        Enabled: 'true'
        Origins:
          - DomainName: !Sub '${SampleBucket}.s3.amazonaws.com'
            Id: !Sub 'S3-${SampleBucket}'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${SampleOriginAccessIdentity}'
        ViewerCertificate:
          AcmCertificateArn: !Ref 'AcmCertificateArn'
          SslSupportMethod: sni-only
    Type: AWS::CloudFront::Distribution
  SampleOriginAccessIdentity:
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: sample
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  SampleRecordSet:
    Properties:
      AliasTarget:
        DNSName: !GetAtt 'SampleDistribution.DomainName'
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: !Ref 'HostZoneId'
      Name: !Ref 'Cname'
      Type: A
    Type: AWS::Route53::RecordSet
